package form;
import java.io.File;
import java.io.FileWriter;
import java.sql.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import javax.swing.JTable;

public class FormLaporan extends javax.swing.JFrame {

    public FormLaporan() {
        initComponents();
    }
private void exportToExcel(String query, String filename) {
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setSelectedFile(new File(filename + ".xls"));
    int userSelection = fileChooser.showSaveDialog(this);

    if (userSelection == JFileChooser.APPROVE_OPTION) {
        try (FileWriter fw = new FileWriter(fileChooser.getSelectedFile())) {
            Connection c = koneksi.Koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet rs = s.executeQuery(query);
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();

            // Tulis Header
            for (int i = 1; i <= columnCount; i++) {
                fw.write(metaData.getColumnName(i) + "\t");
            }
            fw.write("\n");

            // Tulis Data
            while (rs.next()) {
                for (int i = 1; i <= columnCount; i++) {
                    fw.write(rs.getString(i) + "\t");
                }
                fw.write("\n");
            }
            JOptionPane.showMessageDialog(this, "Export Excel Berhasil!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
}
private void exportToPDF(String query, String title) {
    try {
        // 1. Ambil data dari Database
        Connection c = koneksi.Koneksi.getKoneksi();
        Statement s = c.createStatement();
        ResultSet rs = s.executeQuery(query);
        ResultSetMetaData metaData = rs.getMetaData();
        int columnCount = metaData.getColumnCount();

        // 2. Masukkan ke DefaultTableModel
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        for (int i = 1; i <= columnCount; i++) {
            model.addColumn(metaData.getColumnLabel(i));
        }
        while (rs.next()) {
            Object[] row = new Object[columnCount];
            for (int i = 1; i <= columnCount; i++) {
                row[i - 1] = rs.getObject(i);
            }
            model.addRow(row);
        }

        // 3. Gunakan JTable sementara untuk proses Print
        JTable tempTable = new JTable(model);
        
        // 4. Konfigurasi Header dan Footer PDF
        MessageFormat header = new MessageFormat(title);
        MessageFormat footer = new MessageFormat("Halaman {0}");

        // 5. Eksekusi Print (Pilih 'Save as PDF' di dialog printer)
        boolean complete = tempTable.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        
        if (complete) {
            JOptionPane.showMessageDialog(this, "Proses Cetak Selesai");
        }
    } catch (PrinterException | SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal mencetak: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExportAset = new javax.swing.JButton();
        btnExportPeminjaman = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnExportAset.setText("Export Aset");
        btnExportAset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportAsetActionPerformed(evt);
            }
        });

        btnExportPeminjaman.setText("Export Peminjaman");
        btnExportPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportPeminjamanActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("FORM LAPORAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel1)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExportPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExportAset, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExportAset)
                .addGap(18, 18, 18)
                .addComponent(btnExportPeminjaman)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportAsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportAsetActionPerformed
     String sql = "SELECT id_aset AS ID, nama_aset AS Nama, kategori AS Kategori, status AS Status FROM tbl_aset";
    String[] options = {"Excel (.xls)", "PDF (Print)"};
    int choice = JOptionPane.showOptionDialog(this, "Pilih Format Laporan:", "Export Aset",
                 JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);

    if (choice == 0) {
        exportToExcel(sql, "Laporan_Aset");
    } else if (choice == 1) {
        exportToPDF(sql, "LAPORAN DATA ASET");
    }
    }//GEN-LAST:event_btnExportAsetActionPerformed

    private void btnExportPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportPeminjamanActionPerformed
       String sql = "SELECT p.id_peminjaman AS ID, a.nama_aset AS Aset, pg.nama_pegawai AS Pegawai, "
               + "p.tgl_pinjam AS 'Tgl Pinjam', p.status AS Status "
               + "FROM tbl_peminjaman p "
               + "JOIN tbl_aset a ON p.id_aset = a.id_aset "
               + "JOIN tbl_pegawai pg ON p.id_pegawai = pg.id_pegawai";
               
    String[] options = {"Excel (.xls)", "PDF (Print)"};
    int choice = JOptionPane.showOptionDialog(this, "Pilih Format Laporan:", "Export Peminjaman",
                 JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);

    if (choice == 0) {
        exportToExcel(sql, "Laporan_Peminjaman");
    } else if (choice == 1) {
        exportToPDF(sql, "LAPORAN PEMINJAMAN ASET");
    }
    }//GEN-LAST:event_btnExportPeminjamanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLaporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportAset;
    private javax.swing.JButton btnExportPeminjaman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
